//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public int Course_ID { get; set; }
        public Nullable<int> Teacher_ID { get; set; }
        public string CourseName { get; set; }
        public string CourseCode { get; set; }
        public Nullable<int> WhichYear { get; set; }
        public int WhichSemester { get; set; }
        public Nullable<int> NumberOfStudent { get; set; }
        public string TypeOfLesson { get; set; }
    
        public virtual Teacher Teacher { get; set; }
    }
}
