//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unavaliable_Time
    {
        public int Teacher_ID { get; set; }
        public Nullable<bool> Morning { get; set; }
        public Nullable<bool> Noon { get; set; }
        public Nullable<bool> Afternoon { get; set; }
        public Nullable<bool> Evning { get; set; }
        public Nullable<bool> Night { get; set; }
    
        public virtual Teacher Teacher { get; set; }
    }
}
