//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unavailable_Days
    {
        public int Teacher_ID { get; set; }
        public Nullable<bool> MondayMorning { get; set; }
        public Nullable<bool> MondayAfternoon { get; set; }
        public Nullable<bool> TuesdayMorning { get; set; }
        public Nullable<bool> TuesdayAfternoon { get; set; }
        public Nullable<bool> WednesdayMorning { get; set; }
        public Nullable<bool> WednesdayAfternoon { get; set; }
        public Nullable<bool> ThursdayMorning { get; set; }
        public Nullable<bool> ThursdayAfternoon { get; set; }
        public Nullable<bool> FridayMorning { get; set; }
        public Nullable<bool> FridayAfrernoon { get; set; }
    
        public virtual Teacher Teacher { get; set; }
    }
}
